#!/usr/bin/env python3
"""Write the shared site navigation into every page.

The site is static GitHub Pages with no build step, so the header is baked
into each file rather than injected by JS: no SEO cost, no flash of missing
nav. Run this after changing the guide order, the app list, or the markup
below; it rewrites everything between the SAG-NAV markers and leaves the
rest of each file alone.

    python3 build-nav.py

Idempotent. Safe to re-run.
"""

import re
from pathlib import Path

from site_blocks import apply_blocks, render_sitemap
from site_data import (ANALYTICS_TOKEN, APPS, CHANGELOG_PAGE, EXTRA_PAGES,
                       GUIDES, count_word)

ROOT = Path(__file__).parent

START = "<!-- SAG-NAV:START — generated by build-nav.py, do not hand-edit -->"
END = "<!-- SAG-NAV:END -->"

BEACON_START = "<!-- SAG-ANALYTICS:START — generated by build-nav.py -->"
BEACON_END = "<!-- SAG-ANALYTICS:END -->"
BEACON_SRC = "https://static.cloudflareinsights.com/beacon.min.js"

CHEVRON = ('<svg width="11" height="11" viewBox="0 0 24 24" fill="none" '
           'stroke="currentColor" stroke-width="3" stroke-linecap="round" '
           'stroke-linejoin="round" aria-hidden="true"><path d="m6 9 6 6 6-6"/></svg>')

MAGNIFIER = ('<svg width="14" height="14" viewBox="0 0 24 24" fill="none" '
             'stroke="currentColor" stroke-width="2.5" stroke-linecap="round" '
             'aria-hidden="true"><circle cx="11" cy="11" r="7"/><path d="m21 21-4.3-4.3"/></svg>')

BURGER = ('<svg width="17" height="17" viewBox="0 0 24 24" fill="none" '
          'stroke="currentColor" stroke-width="2.5" stroke-linecap="round" '
          'aria-hidden="true"><path d="M3 6h18M3 12h18M3 18h18"/></svg>')

NEW_BADGE = '<span class="sag-new">NEW</span>'


def guide_index(page):
    for i, (f, *_rest) in enumerate(GUIDES):
        if f == page:
            return i
    return None


def build_header(page):
    """The header markup for one page."""
    gi = guide_index(page)
    path_head = f"The path &middot; {count_word(len(GUIDES))} guides, in order"
    apps_head = f"{count_word(len(APPS)).capitalize()} working tools"
    is_home = page == "index.html"
    home = "index.html" if not is_home else "#"

    # Guides dropdown
    items = []
    for i, (f, title, mins, is_new) in enumerate(GUIDES):
        active = ' active' if f == page else ''
        badge = NEW_BADGE if is_new else ''
        items.append(
            f'<a class="sag-g{active}" role="menuitem" href="{f}">'
            f'<em>{i + 1:02d}</em><span>{title}{badge}</span><i>{mins}</i></a>'
        )
    guides_html = "\n            ".join(items)

    # Apps dropdown
    apps = []
    for url, name, who, is_new in APPS:
        badge = NEW_BADGE if is_new else ''
        apps.append(
            f'<a class="sag-a" role="menuitem" href="{url}">'
            f'<strong>{name}{badge}</strong><span>{who}</span></a>'
        )
    apps_html = "\n          ".join(apps)

    # One context-aware CTA.
    if gi is not None and gi + 1 < len(GUIDES):
        nxt_file, nxt_title, _, _ = GUIDES[gi + 1]
        cta_href, cta_text = nxt_file, f"Next: {nxt_title} &rarr;"
    elif gi is not None:
        cta_href, cta_text = home, "Back to all guides &rarr;"
    else:
        cta_href, cta_text = "prompting.html", "Read the guide &rarr;"

    trainer = "#trainer" if is_home else "index.html#trainer"
    about_active = ' active' if page == "people.html" else ''
    news_active = ' active' if page == CHANGELOG_PAGE else ''

    # Mobile sheet mirrors the desktop groups.
    sheet_guides = []
    for i, (f, title, mins, is_new) in enumerate(GUIDES):
        active = ' class="active"' if f == page else ''
        badge = NEW_BADGE if is_new else ''
        sheet_guides.append(
            f'<a href="{f}"{active}><em>{i + 1:02d}</em>{title}{badge}<small>{mins}</small></a>'
        )
    sheet_guides_html = "\n        ".join(sheet_guides)

    sheet_apps = "\n        ".join(
        f'<a href="{url}">{name}{NEW_BADGE if is_new else ""}<small>{who}</small></a>'
        for url, name, who, is_new in APPS
    )

    header = f'''{START}
<header class="sag-nav">
  <div class="sag-nav-inner">
    <a class="sag-brand" href="{home}" aria-label="Steve's AI Guide, home">
      <span class="sag-brand-mark" aria-hidden="true">S</span>
      <span class="sag-brand-text"><b>Steve's</b> <i>AI</i> <b>Guide</b></span>
    </a>

    <nav class="sag-menu" aria-label="Main">
      <div class="sag-dd">
        <button class="sag-dd-btn" type="button" aria-expanded="false" aria-haspopup="true" aria-controls="sagGuides">Guides {CHEVRON}</button>
        <div class="sag-dd-panel sag-dd-guides" id="sagGuides" role="menu">
          <span class="sag-dd-head">{path_head}</span>
          <div class="sag-dd-cols">
            {guides_html}
          </div>
        </div>
      </div>

      <div class="sag-dd">
        <button class="sag-dd-btn" type="button" aria-expanded="false" aria-haspopup="true" aria-controls="sagApps">Apps {CHEVRON}</button>
        <div class="sag-dd-panel sag-dd-apps" id="sagApps" role="menu">
          <span class="sag-dd-head">{apps_head}</span>
          {apps_html}
        </div>
      </div>

      <a class="sag-link" href="{trainer}">Trainer</a>
      <a class="sag-link{news_active}" href="{CHANGELOG_PAGE}">What&rsquo;s new</a>
      <a class="sag-link{about_active}" href="people.html">About</a>
    </nav>

    <div class="sag-right">
      <button class="sag-search" type="button" aria-label="Search the guides">{MAGNIFIER}<span>Search</span><kbd>&#8984;K</kbd></button>
      <a class="sag-cta" href="{cta_href}">{cta_text}</a>
      <button class="sag-burger" type="button" id="sagBurger" aria-label="Open menu" aria-expanded="false" aria-controls="sagSheet">{BURGER}</button>
    </div>
  </div>

</header>

<!-- The sheet is a SIBLING of the header, not a child: .sag-nav sets
     backdrop-filter, which makes it the containing block for any
     position:fixed descendant, and the sheet collapsed to nav height. -->
<div class="sag-sheet" id="sagSheet">
  <span class="sag-sheet-group">{path_head}</span>
      {sheet_guides_html}
  <span class="sag-sheet-group">The apps</span>
      {sheet_apps}
  <span class="sag-sheet-group">More</span>
      <a href="{trainer}">Prompt Trainer</a>
      <a href="{CHANGELOG_PAGE}">What&rsquo;s new</a>
      <a href="people.html">People I learn from</a>
      <a class="sag-sheet-cta" href="{cta_href}">{cta_text}</a>
</div>
'''

    # Progress rail: sequenced guide pages only.
    if gi is not None:
        _, title, _, _ = GUIDES[gi]
        pct = round((gi + 1) / len(GUIDES) * 100)
        if gi + 1 < len(GUIDES):
            nxt_file, nxt_title, _, _ = GUIDES[gi + 1]
            nxt = f'<a class="sag-rail-next" href="{nxt_file}">Next: {nxt_title} &rarr;</a>'
        else:
            nxt = f'<a class="sag-rail-next" href="{home}">All guides &rarr;</a>'
        header += f'''<div class="sag-rail">
  <div class="sag-rail-inner">
    <span class="sag-rail-pos">Guide {gi + 1} of {len(GUIDES)}</span>
    <span class="sag-rail-title">{title}</span>
    <span class="sag-rail-bar" role="progressbar" aria-valuenow="{gi + 1}" aria-valuemin="1" aria-valuemax="{len(GUIDES)}" aria-label="Progress through the path"><span style="width:{pct}%"></span></span>
    {nxt}
  </div>
</div>
'''

    return header + END


# Old navs this replaces.
OLD_NAV_PATTERNS = [
    re.compile(r'<!-- ─+ NAV ─+ -->\s*<nav class="top">.*?</nav>\s*', re.S),
    re.compile(r'<nav class="resource-nav">.*?</nav>\s*', re.S),
]

MARKER_RE = re.compile(re.escape(START) + r".*?" + re.escape(END) + r"\s*", re.S)
BEACON_RE = re.compile(re.escape(BEACON_START) + r".*?" + re.escape(BEACON_END) + r"\s*", re.S)
BODY_RE = re.compile(r"(<body[^>]*>)")


def build_beacon():
    """The analytics tag, or nothing while no token is set."""
    beacon = ""
    if ANALYTICS_TOKEN:
        beacon = (
            f"{BEACON_START}\n"
            f'<script defer src="{BEACON_SRC}" '
            f"data-cf-beacon='{{\"token\": \"{ANALYTICS_TOKEN}\"}}'></script>\n"
            f"{BEACON_END}\n"
        )
    return beacon


def process(path: Path) -> str:
    src = original = path.read_text(encoding="utf-8")
    page = path.name
    notes = []

    # Remove a previously generated block so re-runs stay clean.
    src, n = MARKER_RE.subn("", src)
    if n:
        notes.append("replaced")

    # Remove the legacy navs.
    for pat in OLD_NAV_PATTERNS:
        src, n = pat.subn("", src)
        if n:
            notes.append(f"dropped {n} legacy nav")

    # Link the shared assets once.
    if 'href="nav.css"' not in src:
        src = src.replace("</head>", '  <link rel="stylesheet" href="nav.css">\n</head>', 1)
        notes.append("+nav.css")
    if 'src="nav.js"' not in src:
        src = src.replace("</body>", '<script src="nav.js" defer></script>\n</body>', 1)
        notes.append("+nav.js")
    if 'src="search.js"' not in src:
        src = src.replace("</body>", '<script src="search.js" defer></script>\n</body>', 1)
        notes.append("+search.js")

    # Analytics tag: rewritten each run so a token change reaches every page.
    src = BEACON_RE.sub("", src)
    src = src.replace("</body>", build_beacon() + "</body>", 1)

    src = apply_blocks(page, src)

    block = build_header(page)
    m = BODY_RE.search(src)
    if not m:
        raise SystemExit(f"{page}: no <body> tag")
    src = src[:m.end()] + "\n" + block + "\n" + src[m.end():]

    if src != original:
        path.write_text(src, encoding="utf-8")
    return ", ".join(notes) or "nav written"


def main():
    pages = [f for f, *_ in GUIDES] + EXTRA_PAGES
    missing = [p for p in pages if not (ROOT / p).exists()]
    if missing:
        raise SystemExit("missing pages: " + ", ".join(missing))
    for p in sorted(pages):
        print(f"  {p:<34} {process(ROOT / p)}")
    (ROOT / "sitemap.xml").write_text(render_sitemap(), encoding="utf-8")
    print(f"\n{len(pages)} pages carry the shared nav. sitemap.xml written.")


if __name__ == "__main__":
    main()
