#!/usr/bin/env python3
"""Write the shared site navigation into every page.

The site is static GitHub Pages with no build step, so the header is baked
into each file rather than injected by JS: no SEO cost, no flash of missing
nav. Run this after changing the guide order, the app list, or the markup
below; it rewrites everything between the SAG-NAV markers and leaves the
rest of each file alone.

    python3 build-nav.py

Idempotent. Safe to re-run.
"""

import re
import sys
from pathlib import Path

ROOT = Path(__file__).parent

START = "<!-- SAG-NAV:START — generated by build-nav.py, do not hand-edit -->"
END = "<!-- SAG-NAV:END -->"

# The path, in reading order. Read times come from the homepage ramp cards.
GUIDES = [
    ("prompting.html", "The Prompting Guide", "45 min", False),
    ("beginner.html", "Claude Beginner", "35 min", False),
    ("level-2.html", "Claude Advanced", "50 min", False),
    ("workflows.html", "Claude in Action", "30 min", False),
    ("claude-code-2.html", "Claude Code 2.0", "40 min", False),
    ("claude-design.html", "Claude Design", "35 min", False),
    ("claude-office.html", "Claude in Office", "30 min", False),
    ("claude-writing.html", "Claude Writing", "25 min", True),
    ("claude-everywhere.html", "Claude Everywhere", "20 min", False),
]

APPS = [
    ("https://keyroom.stevesaiguide.com", "Keyroom", "Residential real estate", False),
    ("https://boardroom.stevesaiguide.com", "Boardroom", "Commercial real estate", False),
    ("https://toolroom.stevesaiguide.com", "Toolroom", "Builders &amp; GCs", False),
    ("https://righthand.stevesaiguide.com", "Righthand", "Executive assistants", True),
    ("https://students.stevesaiguide.com", "Recall", "Students", True),
]

# Pages that get the nav but sit outside the path.
EXTRA_PAGES = [
    "index.html",
    "people.html",
    "follow-up-tracker.html",
    "linkedin-audience-simulator.html",
    "linkedin-content-engine.html",
    "linkedin-feed-tracker.html",
]

CHEVRON = ('<svg width="11" height="11" viewBox="0 0 24 24" fill="none" '
           'stroke="currentColor" stroke-width="3" stroke-linecap="round" '
           'stroke-linejoin="round" aria-hidden="true"><path d="m6 9 6 6 6-6"/></svg>')

MAGNIFIER = ('<svg width="14" height="14" viewBox="0 0 24 24" fill="none" '
             'stroke="currentColor" stroke-width="2.5" stroke-linecap="round" '
             'aria-hidden="true"><circle cx="11" cy="11" r="7"/><path d="m21 21-4.3-4.3"/></svg>')

BURGER = ('<svg width="17" height="17" viewBox="0 0 24 24" fill="none" '
          'stroke="currentColor" stroke-width="2.5" stroke-linecap="round" '
          'aria-hidden="true"><path d="M3 6h18M3 12h18M3 18h18"/></svg>')

NEW_BADGE = '<span class="sag-new">NEW</span>'


def guide_index(page):
    for i, (f, *_rest) in enumerate(GUIDES):
        if f == page:
            return i
    return None


def build_header(page):
    """The header markup for one page."""
    gi = guide_index(page)
    is_home = page == "index.html"
    home = "index.html" if not is_home else "#"

    # Guides dropdown
    items = []
    for i, (f, title, mins, is_new) in enumerate(GUIDES):
        active = ' active' if f == page else ''
        badge = NEW_BADGE if is_new else ''
        items.append(
            f'<a class="sag-g{active}" role="menuitem" href="{f}">'
            f'<em>{i + 1:02d}</em><span>{title}{badge}</span><i>{mins}</i></a>'
        )
    guides_html = "\n            ".join(items)

    # Apps dropdown
    apps = []
    for url, name, who, is_new in APPS:
        badge = NEW_BADGE if is_new else ''
        apps.append(
            f'<a class="sag-a" role="menuitem" href="{url}">'
            f'<strong>{name}{badge}</strong><span>{who}</span></a>'
        )
    apps_html = "\n          ".join(apps)

    # One context-aware CTA.
    if gi is not None and gi + 1 < len(GUIDES):
        nxt_file, nxt_title, _, _ = GUIDES[gi + 1]
        cta_href, cta_text = nxt_file, f"Next: {nxt_title} &rarr;"
    elif gi is not None:
        cta_href, cta_text = home, "Back to all guides &rarr;"
    else:
        cta_href, cta_text = "prompting.html", "Read the guide &rarr;"

    trainer = "#trainer" if is_home else "index.html#trainer"
    about_active = ' active' if page == "people.html" else ''

    # Mobile sheet mirrors the desktop groups.
    sheet_guides = []
    for i, (f, title, mins, is_new) in enumerate(GUIDES):
        active = ' class="active"' if f == page else ''
        badge = NEW_BADGE if is_new else ''
        sheet_guides.append(
            f'<a href="{f}"{active}><em>{i + 1:02d}</em>{title}{badge}<small>{mins}</small></a>'
        )
    sheet_guides_html = "\n        ".join(sheet_guides)

    sheet_apps = "\n        ".join(
        f'<a href="{url}">{name}{NEW_BADGE if is_new else ""}<small>{who}</small></a>'
        for url, name, who, is_new in APPS
    )

    header = f'''{START}
<header class="sag-nav">
  <div class="sag-nav-inner">
    <a class="sag-brand" href="{home}" aria-label="Steve's AI Guide, home">
      <span class="sag-brand-mark" aria-hidden="true">S</span>
      <span class="sag-brand-text"><b>Steve's</b> <i>AI</i> <b>Guide</b></span>
    </a>

    <nav class="sag-menu" aria-label="Main">
      <div class="sag-dd">
        <button class="sag-dd-btn" type="button" aria-expanded="false" aria-haspopup="true" aria-controls="sagGuides">Guides {CHEVRON}</button>
        <div class="sag-dd-panel sag-dd-guides" id="sagGuides" role="menu">
          <span class="sag-dd-head">The path &middot; nine guides, in order</span>
          <div class="sag-dd-cols">
            {guides_html}
          </div>
        </div>
      </div>

      <div class="sag-dd">
        <button class="sag-dd-btn" type="button" aria-expanded="false" aria-haspopup="true" aria-controls="sagApps">Apps {CHEVRON}</button>
        <div class="sag-dd-panel sag-dd-apps" id="sagApps" role="menu">
          <span class="sag-dd-head">Five working tools</span>
          {apps_html}
        </div>
      </div>

      <a class="sag-link" href="{trainer}">Trainer</a>
      <a class="sag-link{about_active}" href="people.html">About</a>
    </nav>

    <div class="sag-right">
      <button class="sag-search" type="button" aria-label="Search the guides">{MAGNIFIER}<span>Search</span><kbd>&#8984;K</kbd></button>
      <a class="sag-cta" href="{cta_href}">{cta_text}</a>
      <button class="sag-burger" type="button" id="sagBurger" aria-label="Open menu" aria-expanded="false" aria-controls="sagSheet">{BURGER}</button>
    </div>
  </div>

</header>

<!-- The sheet is a SIBLING of the header, not a child: .sag-nav sets
     backdrop-filter, which makes it the containing block for any
     position:fixed descendant, and the sheet collapsed to nav height. -->
<div class="sag-sheet" id="sagSheet">
  <span class="sag-sheet-group">The path &middot; nine guides, in order</span>
      {sheet_guides_html}
  <span class="sag-sheet-group">The apps</span>
      {sheet_apps}
  <span class="sag-sheet-group">More</span>
      <a href="{trainer}">Prompt Trainer</a>
      <a href="people.html">People I learn from</a>
      <a class="sag-sheet-cta" href="{cta_href}">{cta_text}</a>
</div>
'''

    # Progress rail: sequenced guide pages only.
    if gi is not None:
        _, title, _, _ = GUIDES[gi]
        pct = round((gi + 1) / len(GUIDES) * 100)
        if gi + 1 < len(GUIDES):
            nxt_file, nxt_title, _, _ = GUIDES[gi + 1]
            nxt = f'<a class="sag-rail-next" href="{nxt_file}">Next: {nxt_title} &rarr;</a>'
        else:
            nxt = f'<a class="sag-rail-next" href="{home}">All guides &rarr;</a>'
        header += f'''<div class="sag-rail">
  <div class="sag-rail-inner">
    <span class="sag-rail-pos">Guide {gi + 1} of {len(GUIDES)}</span>
    <span class="sag-rail-title">{title}</span>
    <span class="sag-rail-bar" role="progressbar" aria-valuenow="{gi + 1}" aria-valuemin="1" aria-valuemax="{len(GUIDES)}" aria-label="Progress through the path"><span style="width:{pct}%"></span></span>
    {nxt}
  </div>
</div>
'''

    return header + END


# Old navs this replaces.
OLD_NAV_PATTERNS = [
    re.compile(r'<!-- ─+ NAV ─+ -->\s*<nav class="top">.*?</nav>\s*', re.S),
    re.compile(r'<nav class="resource-nav">.*?</nav>\s*', re.S),
]

MARKER_RE = re.compile(re.escape(START) + r".*?" + re.escape(END) + r"\s*", re.S)
BODY_RE = re.compile(r"(<body[^>]*>)")


def process(path: Path) -> str:
    src = original = path.read_text(encoding="utf-8")
    page = path.name
    notes = []

    # Remove a previously generated block so re-runs stay clean.
    src, n = MARKER_RE.subn("", src)
    if n:
        notes.append("replaced")

    # Remove the legacy navs.
    for pat in OLD_NAV_PATTERNS:
        src, n = pat.subn("", src)
        if n:
            notes.append(f"dropped {n} legacy nav")

    # Link the shared assets once.
    if 'href="nav.css"' not in src:
        src = src.replace("</head>", '  <link rel="stylesheet" href="nav.css">\n</head>', 1)
        notes.append("+nav.css")
    if 'src="nav.js"' not in src:
        src = src.replace("</body>", '<script src="nav.js" defer></script>\n</body>', 1)
        notes.append("+nav.js")
    if 'src="search.js"' not in src:
        src = src.replace("</body>", '<script src="search.js" defer></script>\n</body>', 1)
        notes.append("+search.js")

    block = build_header(page)
    m = BODY_RE.search(src)
    if not m:
        raise SystemExit(f"{page}: no <body> tag")
    src = src[:m.end()] + "\n" + block + "\n" + src[m.end():]

    if src != original:
        path.write_text(src, encoding="utf-8")
    return ", ".join(notes) or "nav written"


def main():
    pages = [f for f, *_ in GUIDES] + EXTRA_PAGES
    missing = [p for p in pages if not (ROOT / p).exists()]
    if missing:
        raise SystemExit("missing pages: " + ", ".join(missing))
    for p in sorted(pages):
        print(f"  {p:<34} {process(ROOT / p)}")
    print(f"\n{len(pages)} pages carry the shared nav.")


if __name__ == "__main__":
    main()
